import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowRight, Ruler } from 'lucide-react';
import { settings } from '@/lib/catalog';
export const dynamicParams = false;
const content:Record<string,{title:string;eyebrow:string;intro:string;sections:{title:string;text:string}[]}>= {
  'size-guide':{title:'FIND YOUR FIT.',eyebrow:'SIZING / BEFORE YOU ORDER',intro:'A good fit starts with the actual garment. Manufacturer size charts will be added when our tee and hoodie blanks are selected.',sections:[{title:'Measure a favorite you already own',text:'Lay a similar garment flat. Measure straight across the chest from underarm to underarm, then from the high shoulder to the bottom hem. Compare those measurements with the final product’s chart when available.'},{title:'Different garments, different fits',text:'Tees and hoodies will have their own size charts. Proposed sizes are S–4XL, subject to the selected garment and color. We will confirm measurements and availability before accepting orders.'}]},
  'shipping-returns':{title:'THE DETAILS MATTER.',eyebrow:'SHIPPING & RETURNS',intro:'The collection is in development. We are not accepting orders yet, and shipping or return terms have not been finalized.',sections:[{title:'Shipping',text:'Delivery regions, rates, production time, and any free-shipping offer will be published before launch. Items produced in different locations may ship separately, with tracking for each package.'},{title:'Returns & exchanges',text:'The final policy will explain eligibility, timeframes, return shipping, and how we handle damaged or incorrect items. Please do not treat the concept store as a promise of a particular return policy.'},{title:'Questions in the meantime',text:'Contact TechSavvy at support@techsavvytechs.com. We can discuss the collection while the production details take shape.'}]},
  'track-order':{title:'FOLLOW YOUR GEAR.',eyebrow:'ORDER TRACKING',intro:'Order tracking will open when the store starts accepting orders.',sections:[{title:'No orders are being taken yet',text:'Items added to the preview bag are saved on your device only. They do not create an order, charge your card, or reserve inventory.'},{title:'Already speaking with TechSavvy?',text:'If you arranged something directly with our team, contact support@techsavvytechs.com for an update. Please do not send payment information by email.'}]},
  'checkout':{title:'ALMOST READY TO WEAR.',eyebrow:'COLLECTION PREVIEW / ORDERING NOT OPEN',intro:'Thanks for exploring the first collection. Checkout will open after physical samples, final pricing, and fulfillment are ready.',sections:[{title:'Your preview bag is saved',text:'Your selections stay in this browser when local storage is available. No order has been placed and no payment has been collected.'},{title:'Interested in being part of the launch?',text:'Visit our partnership page to start a conversation about production, collaboration, or the business behind the gear.'}]},
  'privacy':{title:'YOUR PRIVACY.',eyebrow:'PREVIEW SITE / PRIVACY',intro:'This version of TechSavvy Gear is a collection preview. It does not accept payments or create customer accounts.',sections:[{title:'What this site stores',text:'The preview bag uses your browser’s local storage to remember product selections, sizes, colors, and quantities. You can remove those selections in the bag or clear this site’s browser storage.'},{title:'Contact forms',text:'The forms prepare a message in your browser. They do not submit your information to a database. If you choose to send the message through your email app, TechSavvy receives the information you include and uses it to respond to your inquiry.'},{title:'Hosting & future services',text:'The hosting provider may process standard request information, such as IP addresses and access logs, to serve and protect the site. No marketing analytics or advertising scripts have been added to this preview. This notice will be reviewed before payments, accounts, or other integrations are enabled.'},{title:'Contact',text:'For questions about this preview or information you have sent us, email support@techsavvytechs.com.'}]},
  'terms':{title:'A FIRST LOOK.',eyebrow:'PREVIEW SITE / TERMS',intro:'TechSavvy Gear is currently a marketing and product-concept preview operated by TechSavvy LLC.',sections:[{title:'Product concepts',text:'Images are design references, not photographs of approved production samples. Prices, garments, colors, sizes, artwork placement, and availability may change before launch.'},{title:'No purchases or reservations',text:'Adding items to the preview bag does not place an order, reserve inventory, or establish an agreement to sell. No payments are accepted in this version.'},{title:'Partnership conversations',text:'Information on the partnership page is an invitation to discuss opportunities. It is not a promise of a business arrangement or an investment offering.'},{title:'Before ordering opens',text:'Final purchase terms, shipping details, return policies, and applicable privacy disclosures will be made available before the store accepts orders.'}]}
};
export function generateStaticParams(){return Object.keys(content).map(page=>({page}));}
export async function generateMetadata({params}:{params:Promise<{page:string}>}){const {page}=await params;return {title:content[page]?.eyebrow.split('/')[0].trim()||'Page not found',alternates:{canonical:`/${page}`},...(page==='checkout'?{robots:{index:false,follow:true}}:{})};}
export default async function InfoPage({params}:{params:Promise<{page:string}>}){const {page}=await params;const c=content[page];if(!c)notFound();return <section className="shell section info-page"><div className="page-intro"><span className="eyebrow">{c.eyebrow}</span><h1>{c.title}</h1><p className="lead">{c.intro}</p></div>{page==='size-guide'&&<div className="measurement-note"><Ruler size={40}/><div><h3>Measure flat. Compare like for like.</h3><p>Chest: underarm → underarm<br/>Length: high shoulder → bottom hem</p></div></div>}<div className="info-sections">{c.sections.map(s=><section key={s.title}><h2>{s.title}</h2><p>{s.text}</p></section>)}</div><div className="info-actions"><Link className="button button-green" href={page==='checkout'?'/partners':'/shop'}>{page==='checkout'?'EXPLORE PARTNERSHIPS':'EXPLORE THE COLLECTION'}<ArrowRight size={18}/></Link><a href={`mailto:${settings.email}`} className="text-link">Contact TechSavvy <ArrowRight size={16}/></a></div></section>;}
