import { useEffect, useMemo, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { CalendarDays, CheckCircle2, CircleDollarSign, FileText, FileUp, HardHat, LifeBuoy, MapPin, ShieldCheck, Wrench, XCircle } from "lucide-react";

type PortalData = {
  preview?: boolean;
  customer: { name: string; contact: string; email: string; phone: string; sites: string[] };
  jobs: { id: string; number: string; title: string; site: string; status: string; technician: string; targetCompletion: string; schedule?: { date?: string; start?: string; end?: string } }[];
  quotes: { id: string; number: string; title: string; site: string; status: string; total: number }[];
  invoices: { id: string; number: string; status: string; issueDate: string; dueDate: string; total: number; balance: number; paymentLink?: string; onlinePaymentEnabled: boolean }[];
  assets: { id: string; name: string; site: string; category: string; manufacturer: string; model: string; serialNumber: string; status: string; nextServiceDate: string; fulfillmentSource?: string; workOrderNumber?: string; quantity?: string }[];
};

const money = (value = 0) => value.toLocaleString(undefined, { style: "currency", currency: "USD" });
const badge = (status: string) => status === "Paid" || status === "Complete" || status === "Accepted" ? "bg-green-100 text-green-800" : status === "Overdue" || status === "Rejected" ? "bg-red-100 text-red-700" : "bg-orange-100 text-orange-700";
const emptyRequest = { subject: "", message: "", site: "", address: "", siteContact: "", clientReference: "", serviceType: "low-voltage", accessInstructions: "", safetyRequirements: "", preferredDate: "" };

async function encodeFiles(files: File[]) {
  return Promise.all(files.map((file) => new Promise<{ name: string; contentType: string; data: string }>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve({ name: file.name, contentType: file.type || "application/octet-stream", data: String(reader.result) });
    reader.onerror = () => reject(new Error(`Could not read ${file.name}.`));
    reader.readAsDataURL(file);
  })));
}

export default function CustomerPortal() {
  const token = useMemo(() => new URLSearchParams(window.location.search).get("token") || "", []);
  const [data, setData] = useState<PortalData | null>(null);
  const [error, setError] = useState("");
  const [tab, setTab] = useState<"overview" | "jobs" | "billing" | "assets" | "request">("overview");
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const [submittedRequestNumber, setSubmittedRequestNumber] = useState("");
  const [request, setRequest] = useState(emptyRequest);
  const [scopeTasks, setScopeTasks] = useState([""]);
  const [deliverables, setDeliverables] = useState<string[]>([]);
  const [deliverableType, setDeliverableType] = useState<"Photo" | "Document">("Photo");
  const [deliverableDetail, setDeliverableDetail] = useState("");
  const [equipment, setEquipment] = useState([{ description: "", quantity: "", notes: "", fulfillmentSource: "customer_shipped" }]);
  const [requestFiles, setRequestFiles] = useState<File[]>([]);

  useEffect(() => {
    if (!token) { setError("This customer portal link is incomplete."); return; }
    fetch(`/api/contact?operation=customer-portal&token=${encodeURIComponent(token)}`)
      .then(async (response) => { const value = await response.json(); if (!response.ok) throw new Error(value.error || "The portal could not be loaded."); setData(value); })
      .catch((reason) => setError(reason.message));
  }, [token]);
  useEffect(() => {
    if (!sent) return;
    const timeout = window.setTimeout(() => setSent(false), 12000);
    return () => window.clearTimeout(timeout);
  }, [sent]);

  const submitRequest = async (event: FormEvent) => {
    event.preventDefault(); setSending(true);
    try {
      const attachments = await encodeFiles(requestFiles);
      const response = await fetch("/api/contact?operation=portal-service-request", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, ...request, scopeTasks, requiredDeliverables: deliverables, equipment, attachments }) });
      const value = await response.json();
      if (!response.ok) throw new Error(value.error || "The service request could not be sent.");
      setSubmittedRequestNumber(`CP-${String(value.requestId || "").slice(-6).toUpperCase()}`); setSent(true); setRequest(emptyRequest); setScopeTasks([""]); setDeliverables([]); setDeliverableDetail(""); setEquipment([{ description: "", quantity: "", notes: "", fulfillmentSource: "customer_shipped" }]); setRequestFiles([]);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "The service request could not be sent."); }
    finally { setSending(false); }
  };

  if (error) return <div className="grid min-h-screen place-items-center bg-[#0b0f0c] p-5"><div className="max-w-md rounded border border-red-500/20 bg-[#151916] p-8 text-center text-white"><XCircle className="mx-auto h-10 w-10 text-red-400"/><h1 className="mt-4 font-display text-xl uppercase">Portal unavailable</h1><p className="mt-3 text-sm text-slate-400">{error}</p><a href="mailto:support@techsavvytechs.com" className="mt-5 inline-block text-xs font-bold text-tech-green">Contact TechSavvy support</a></div></div>;
  if (!data) return <div className="grid min-h-screen place-items-center bg-[#0b0f0c] text-sm text-slate-400">Verifying secure portal access…</div>;

  const outstanding = data.invoices.reduce((sum, invoice) => sum + invoice.balance, 0);
  const nextVisit = data.jobs.find((job) => job.schedule?.date || job.targetCompletion);
  const nav = [["overview", "Overview"], ["jobs", "Jobs"], ["billing", "Quotes & billing"], ["assets", "Assets"], ["request", "Request service"]] as const;
  return <div className="min-h-screen bg-[#eef2ef] text-slate-900">
    <header className="bg-[#0b0f0c] text-white"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-5 px-5 py-6 sm:flex-row sm:items-center"><div><p className="font-display text-xl uppercase text-tech-green">TechSavvy</p><p className="text-[9px] uppercase tracking-[.24em] text-slate-400">Customer Portal</p></div><div className="sm:text-right"><p className="text-xs font-bold">{data.customer.name}</p><p className="text-[10px] text-slate-400">Secure account access</p></div></div></header>
    <nav className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl gap-1 overflow-x-auto px-4">{nav.map(([id, label]) => <button key={id} onClick={() => { setTab(id); if (id !== "request") setSent(false); }} className={`whitespace-nowrap border-b-2 px-4 py-4 text-[10px] font-bold uppercase tracking-wide ${tab === id ? "border-tech-green text-tech-green-deep" : "border-transparent text-slate-400"}`}>{label}</button>)}</div></nav>
    {sent && <div role="alert" aria-live="assertive" className="fixed inset-x-4 top-4 z-[100] mx-auto max-w-3xl rounded-xl border-2 border-green-400 bg-green-700 p-5 text-white shadow-2xl sm:top-6"><div className="flex items-start gap-4"><CheckCircle2 className="mt-0.5 h-8 w-8 shrink-0"/><div className="flex-1"><p className="text-lg font-black">Service request submitted</p><p className="mt-1 text-sm text-green-50">Your request {submittedRequestNumber && <strong>{submittedRequestNumber}</strong>} was sent to TechSavvy for review. You may safely leave this page.</p><p className="mt-2 text-xs text-green-100">This message will close automatically.</p></div><button type="button" onClick={()=>setSent(false)} aria-label="Close submission confirmation" className="rounded border border-white/30 px-3 py-1.5 text-xs font-bold">Close</button></div></div>}
    <main className="mx-auto max-w-6xl p-5 sm:p-8">
      {data.preview && <div className="mb-5 flex items-center gap-3 rounded border border-orange-200 bg-orange-50 p-4 text-xs text-orange-800"><ShieldCheck className="h-4 w-4"/><div><b>Administrator preview</b><p className="mt-0.5 text-[10px]">Read-only view. Payments and service-request submission are disabled.</p></div></div>}
      {tab === "overview" && <><div className="mb-6"><h1 className="font-display text-2xl uppercase">Welcome{data.customer.contact ? `, ${data.customer.contact}` : ""}</h1><p className="mt-1 text-xs text-slate-500">Your jobs, equipment, proposals and billing in one place.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={HardHat} label="Active jobs" value={String(data.jobs.filter((j) => !["Complete", "Cancelled"].includes(j.status)).length)} detail={nextVisit ? `Next: ${nextVisit.schedule?.date || nextVisit.targetCompletion}` : "No visit scheduled"}/><Stat icon={FileText} label="Open quotes" value={String(data.quotes.filter((q) => !["Accepted", "Rejected"].includes(q.status)).length)} detail="Awaiting a decision"/><Stat icon={CircleDollarSign} label="Balance due" value={money(outstanding)} detail={outstanding ? "Online payment where enabled" : "Account is current"}/><Stat icon={Wrench} label="Managed assets" value={String(data.assets.length)} detail={`${data.assets.filter((a) => a.nextServiceDate).length} on maintenance plans`}/></div>{nextVisit && <section className="mt-6 rounded border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><CalendarDays className="mt-0.5 h-5 w-5 text-tech-green-deep"/><div><p className="text-[9px] font-bold uppercase tracking-wide text-slate-400">Upcoming service</p><h2 className="mt-1 text-sm font-bold">{nextVisit.title}</h2><p className="mt-1 text-xs text-slate-500">{nextVisit.schedule?.date || nextVisit.targetCompletion} {nextVisit.schedule?.start ? `at ${nextVisit.schedule.start}` : ""} · {nextVisit.technician}</p><p className="mt-2 flex items-center gap-1 text-[10px] text-slate-400"><MapPin className="h-3 w-3"/>{nextVisit.site}</p></div></div></section>}</>}
      {tab === "jobs" && <List title="Service jobs" empty="No jobs are available yet.">{data.jobs.map((job) => <Row key={job.id} title={`${job.number} · ${job.title}`} detail={`${job.site}${job.technician ? ` · ${job.technician}` : ""}`} status={job.status} />)}</List>}
      {tab === "billing" && <div className="grid gap-6 lg:grid-cols-2"><List title="Quotes" empty="No quotes are available.">{data.quotes.map((quote) => <Row key={quote.id} title={`${quote.number} · ${quote.title}`} detail={`${quote.site} · ${money(quote.total)}`} status={quote.status}/>)}</List><List title="Invoices" empty="No invoices are available.">{data.invoices.map((invoice) => <div key={invoice.id} className="border-b border-slate-100 p-4 last:border-0"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold">{invoice.number}</p><p className="mt-1 text-[10px] text-slate-400">Due {invoice.dueDate || "—"} · Balance {money(invoice.balance)}</p></div><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${badge(invoice.status)}`}>{invoice.status}</span></div>{invoice.balance > 0 && (invoice.paymentLink ? <a href={invoice.paymentLink} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-2 rounded bg-tech-green px-4 py-2 text-[10px] font-bold text-brand-black">Pay securely with QuickBooks <CircleDollarSign className="h-3.5 w-3.5"/></a> : <p className="mt-3 rounded bg-slate-50 p-2 text-[9px] text-slate-500">Online payment becomes available after this invoice is synced with QuickBooks Payments.</p>)}</div>)}</List></div>}
      {tab === "assets" && <List title="Equipment & maintenance" empty="No customer assets are recorded.">{data.assets.map((asset) => <Row key={asset.id} title={`${asset.quantity ? `${asset.quantity} × ` : ""}${asset.name}`} detail={`${asset.category}${asset.fulfillmentSource ? ` · ${asset.fulfillmentSource === "techsavvy_supplied" ? "TechSavvy supplied" : "Customer shipped"}` : ""}${asset.workOrderNumber ? ` · ${asset.workOrderNumber}` : ""} · ${asset.manufacturer} ${asset.model}${asset.nextServiceDate ? ` · Next service ${asset.nextServiceDate}` : ""}`} status={asset.status}/>)}</List>}
      {tab === "request" && <section className="mx-auto max-w-4xl rounded border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><LifeBuoy className="h-5 w-5 text-tech-green-deep"/><div><h2 className="text-sm font-bold">Request service</h2><p className="text-[10px] text-slate-400">Provide the job details and documents TechSavvy needs to prepare the work order.</p></div></div>{data.preview ? <p className="mt-5 rounded bg-slate-50 p-4 text-xs text-slate-500">Service requests are disabled in administrator preview.</p> : <><form onSubmit={submitRequest} className="mt-5 space-y-6">
        <div className="grid gap-4 md:grid-cols-2"><Field label="Job / request subject" value={request.subject} onChange={(value) => setRequest({...request, subject:value})}/><label className="block text-[10px] font-bold uppercase text-slate-500">Service type<select value={request.serviceType} onChange={(e) => setRequest({...request, serviceType:e.target.value})} className="mt-1 w-full rounded border border-slate-200 p-3 text-xs font-normal normal-case"><option value="low-voltage">Low-voltage</option><option value="network">Network / infrastructure</option><option value="msp">MSP support</option><option value="cell-boosting">Cellular enhancement</option><option value="survey">Site survey</option><option value="other">Other</option></select></label><label className="block text-[10px] font-bold uppercase text-slate-500">Saved site<select value={request.site} onChange={(e) => setRequest({...request, site:e.target.value, address:e.target.value || request.address})} className="mt-1 w-full rounded border border-slate-200 p-3 text-xs font-normal normal-case"><option value="">Choose or enter a new site below</option>{data.customer.sites.map((site) => <option key={site}>{site}</option>)}</select></label><Field label="Customer PO / reference" value={request.clientReference} onChange={(value) => setRequest({...request, clientReference:value})}/><div className="md:col-span-2"><Field label="Full site address" value={request.address} onChange={(value) => setRequest({...request, address:value})}/></div><div className="md:col-span-2"><Field label="Site contact (name, phone, email)" value={request.siteContact} onChange={(value) => setRequest({...request, siteContact:value})}/></div><label className="block text-[10px] font-bold uppercase text-slate-500">Preferred date<input type="date" required value={request.preferredDate} onChange={(e) => setRequest({...request, preferredDate:e.target.value})} className="mt-1 w-full rounded border border-slate-200 p-3 text-xs font-normal"/></label></div>
        <label className="block text-[10px] font-bold uppercase text-slate-500">Scope summary<textarea required rows={5} value={request.message} onChange={(e) => setRequest({...request, message:e.target.value})} className="mt-1 w-full rounded border border-slate-200 p-3 text-xs font-normal normal-case"/></label>
        <div className="rounded border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase text-slate-500">Scope tasks</p><button type="button" onClick={()=>setScopeTasks((items)=>[...items,""])} className="text-[10px] font-bold text-tech-green-deep">+ Add task</button></div><div className="mt-3 space-y-2">{scopeTasks.map((task,index)=><div key={index} className="flex gap-2"><input value={task} onChange={(e)=>setScopeTasks((items)=>items.map((item,itemIndex)=>itemIndex===index?e.target.value:item))} placeholder={`Task ${index+1}`} className="flex-1 rounded border border-slate-200 bg-white p-3 text-xs"/>{scopeTasks.length>1&&<button type="button" onClick={()=>setScopeTasks((items)=>items.filter((_,itemIndex)=>itemIndex!==index))} className="px-2 text-red-500">×</button>}</div>)}</div></div>
        <div className="rounded border border-slate-200 bg-slate-50 p-4"><div><p className="text-[10px] font-bold uppercase text-slate-500">Required deliverables</p><p className="mt-1 text-[10px] text-slate-400">Choose Photo or Document, describe the exact requirement, and add each deliverable separately.</p></div><div className="mt-3 grid gap-2 md:grid-cols-[120px_1fr_auto]"><select value={deliverableType} onChange={(e)=>setDeliverableType(e.target.value as "Photo" | "Document")} className="rounded border border-slate-200 bg-white p-3 text-xs font-bold text-tech-green-deep"><option>Photo</option><option>Document</option></select><input value={deliverableDetail} onChange={(e)=>setDeliverableDetail(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter'){e.preventDefault();const detail=deliverableDetail.trim();const item=`${deliverableType} required: ${detail}`;if(detail&&!deliverables.includes(item))setDeliverables((items)=>[...items,item]);if(detail)setDeliverableDetail("");}}} placeholder={deliverableType==="Photo"?"Describe the required photo, e.g. cash register from the rear":"Describe the required document, e.g. cable test report"} className="rounded border border-slate-200 bg-white p-3 text-xs"/><button type="button" disabled={!deliverableDetail.trim()} onClick={()=>{const detail=deliverableDetail.trim();const item=`${deliverableType} required: ${detail}`;if(detail&&!deliverables.includes(item))setDeliverables((items)=>[...items,item]);if(detail)setDeliverableDetail("");}} className="rounded bg-tech-green px-4 py-3 text-xs font-bold text-brand-black disabled:opacity-40">Add deliverable</button></div>{deliverables.length===0?<p className="mt-3 rounded bg-white p-3 text-xs text-slate-400">No required deliverables added yet.</p>:<ol className="mt-3 space-y-2">{deliverables.map((item,index)=><li key={`${index}-${item}`} className="flex items-center justify-between gap-3 rounded border border-slate-200 bg-white p-3 text-xs"><span><strong className="mr-2 text-tech-green-deep">{index+1}.</strong>{item}</span><button type="button" onClick={()=>setDeliverables((items)=>items.filter((_,itemIndex)=>itemIndex!==index))} className="shrink-0 text-[10px] font-bold text-red-500">Remove</button></li>)}</ol>}</div>
        <div className="grid gap-4 md:grid-cols-2"><label className="block text-[10px] font-bold uppercase text-slate-500">Access / check-in and site instructions<textarea rows={3} value={request.accessInstructions} onChange={(e)=>setRequest({...request, accessInstructions:e.target.value})} className="mt-1 w-full rounded border border-slate-200 p-3 text-xs font-normal normal-case"/></label><label className="block text-[10px] font-bold uppercase text-slate-500">Safety requirements<textarea rows={3} value={request.safetyRequirements} onChange={(e)=>setRequest({...request, safetyRequirements:e.target.value})} className="mt-1 w-full rounded border border-slate-200 p-3 text-xs font-normal normal-case"/></label></div>
        <div className="rounded border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase text-slate-500">Equipment / materials</p><p className="mt-1 text-[10px] text-slate-400">Approved items become job inventory and customer assets when the request is converted to a work order.</p></div><button type="button" onClick={()=>setEquipment((items)=>[...items,{description:"",quantity:"",notes:"",fulfillmentSource:"customer_shipped"}])} className="text-[10px] font-bold text-tech-green-deep">+ Add item</button></div><div className="mt-3 space-y-2">{equipment.map((item,index)=><div key={index} className="grid gap-2 md:grid-cols-[1fr_80px_160px_1fr_auto]"><input value={item.description} onChange={(e)=>setEquipment((items)=>items.map((value,itemIndex)=>itemIndex===index?{...value,description:e.target.value}:value))} placeholder="Description" className="rounded border border-slate-200 bg-white p-3 text-xs"/><input value={item.quantity} onChange={(e)=>setEquipment((items)=>items.map((value,itemIndex)=>itemIndex===index?{...value,quantity:e.target.value}:value))} placeholder="Qty" className="rounded border border-slate-200 bg-white p-3 text-xs"/><select aria-label={`Fulfillment source for item ${index+1}`} value={item.fulfillmentSource} onChange={(e)=>setEquipment((items)=>items.map((value,itemIndex)=>itemIndex===index?{...value,fulfillmentSource:e.target.value}:value))} className="rounded border border-slate-200 bg-white p-3 text-xs"><option value="customer_shipped">Customer shipped</option><option value="techsavvy_supplied">TechSavvy supplied</option></select><input value={item.notes} onChange={(e)=>setEquipment((items)=>items.map((value,itemIndex)=>itemIndex===index?{...value,notes:e.target.value}:value))} placeholder="Notes" className="rounded border border-slate-200 bg-white p-3 text-xs"/>{equipment.length>1&&<button type="button" onClick={()=>setEquipment((items)=>items.filter((_,itemIndex)=>itemIndex!==index))} className="px-2 text-red-500">×</button>}</div>)}</div></div>
        <label className="block rounded border border-dashed border-slate-300 bg-slate-50 p-4 text-xs text-slate-600"><span className="mb-2 flex items-center gap-2 font-bold"><FileUp className="h-4 w-4 text-tech-green-deep"/>Work order documents</span><input type="file" multiple accept=".pdf,.txt,image/jpeg,image/png" onChange={(e)=>setRequestFiles(Array.from(e.target.files||[]).slice(0,2))} className="w-full text-xs"/><span className="mt-2 block text-[10px] text-slate-400">Up to two PDF, JPG, PNG, or text files; 1.5 MB each. These become available to the assigned technician.</span></label>
        <button disabled={sending} className="w-full rounded bg-tech-green px-5 py-3 text-xs font-bold text-brand-black disabled:opacity-50">{sending ? "Sending request…" : "Send complete service request"}</button></form></>}</section>}
      <footer className="mt-10 flex items-center justify-center gap-2 text-[10px] text-slate-400"><ShieldCheck className="h-4 w-4 text-tech-green-deep"/>Secure TechSavvy customer access · support@techsavvytechs.com</footer>
    </main>
  </div>;
}

function Stat({ icon: Icon, label, value, detail }: { icon: typeof HardHat; label: string; value: string; detail: string }) { return <section className="rounded border border-slate-200 bg-white p-4 shadow-sm"><Icon className="h-4 w-4 text-tech-green-deep"/><p className="mt-4 text-[9px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-display text-xl">{value}</p><p className="mt-2 text-[9px] text-slate-400">{detail}</p></section>; }
function List({ title, empty, children }: { title: string; empty: string; children: ReactNode }) { const hasChildren = Array.isArray(children) ? children.length > 0 : Boolean(children); return <section className="overflow-hidden rounded border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-100 p-4"><h2 className="text-sm font-bold">{title}</h2></header>{hasChildren ? children : <p className="p-6 text-xs text-slate-400">{empty}</p>}</section>; }
function Row({ title, detail, status }: { key?: string; title: string; detail: string; status: string }) { return <div className="flex items-start justify-between gap-3 border-b border-slate-100 p-4 last:border-0"><div><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[10px] text-slate-400">{detail}</p></div><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${badge(status)}`}>{status}</span></div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-[10px] font-bold uppercase text-slate-500">{label}<input required value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full rounded border border-slate-200 p-3 text-xs font-normal normal-case"/></label>; }
