import React, { useEffect, useState } from 'react';
import { useSearchParams, Link } from 'react-router';
import { MessageSquare, RefreshCw } from 'lucide-react';

export default function RequestStatus() {
  const [params] = useSearchParams();
  const requestId = params.get('request') || '', token = params.get('token') || '';
  const [data, setData] = useState<any>(null), [message, setMessage] = useState(''), [error, setError] = useState('');
  const load = async () => { const response = await fetch(`/api/client?action=request-status&requestId=${encodeURIComponent(requestId)}&token=${encodeURIComponent(token)}`); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); };
  useEffect(()=>{void load().catch((e)=>setError(e.message));},[requestId,token]);
  if (error) return <div className="min-h-[70vh] grid place-items-center px-6"><div className="glass-card max-w-lg p-8 text-center text-red-200">{error}</div></div>;
  if (!data) return <div className="min-h-[70vh] grid place-items-center text-slate-400"><RefreshCw className="h-5 w-5 animate-spin"/></div>;
  return <div className="px-6 pb-32 pt-32"><div className="mx-auto max-w-3xl space-y-5"><div className="glass-card border-t-4 border-tech-green p-8"><p className="font-mono text-xs text-tech-green">{data.request.requestNumber}</p><h1 className="mt-2 text-3xl font-bold text-white">{data.request.siteName}</h1><p className="mt-2 text-sm text-slate-400">{data.request.companyName}</p><span className="mt-5 inline-block rounded bg-tech-green/10 px-3 py-1 text-xs font-bold capitalize text-tech-green">{data.request.status.replace(/_/g,' ')}</span>{data.request.reviewNote&&<p className="mt-5 rounded border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-200">{data.request.reviewNote}</p>}</div><section className="glass-card p-6"><h2 className="flex items-center gap-2 text-sm font-bold text-white"><MessageSquare className="h-4 w-4 text-tech-green"/>Clarification conversation</h2><div className="my-4 space-y-3">{data.messages.map((item:any)=><div key={item.id} className="rounded bg-white/5 p-3 text-sm text-slate-300">{item.message}</div>)}</div><textarea rows={4} value={message} onChange={(e)=>setMessage(e.target.value)} placeholder="Reply with clarification…" className="w-full rounded border border-white/10 bg-black/20 p-3 text-sm text-white"/><button onClick={async()=>{if(!message.trim())return;const response=await fetch('/api/client?action=request-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId,token,message})});const result=await response.json();if(!response.ok){setError(result.error);return;}setMessage('');setData(result)}} className="mt-3 bg-tech-green px-4 py-2 text-sm font-bold text-brand-black">Send reply</button></section><p className="text-center text-xs text-slate-500">For ongoing access, <Link to="/client" className="text-tech-green">activate the Client Portal</Link>.</p></div></div>;
}
