import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Fingerprint, Heart, Wrench } from 'lucide-react';
import { Artwork } from '@/components/artwork';
import { Catalog } from '@/components/catalog';
export const metadata={alternates:{canonical:'/'}};
export default function Home(){return <>
  <section className="hero"><div className="hero-art"><Artwork crop={{x:282,y:65,w:658,h:408}} alt="TechSavvy apparel concept showing front and back designs with a branded service van" priority/></div><div className="hero-shade"/><div className="shell hero-content"><div className="eyebrow"><span className="tiny-rule"/> TECHSAVVY GEAR / COLLECTION 001</div><h1>PEOPLE<br/>SOLVE TECH.<br/>PEOPLE<br/><span className="green">MATTER MORE.</span></h1><p>For the builders. The troubleshooters.<br/>The people behind the technology.</p><Link href="/shop" className="button button-green">EXPLORE THE COLLECTION <ArrowUpRight size={20}/></Link><div className="hero-foot"><span>ORIGINAL DESIGNS.</span><span>REAL PURPOSE.</span></div></div><div className="hero-caption">THE FIRST COLLECTION / DESIGN PREVIEW</div></section>
  <div className="mission-ticker"><div className="shell"><span>DESIGN.</span><span>DEPLOY.</span><span>SUPPORT.</span><span>REPEAT.</span><span className="ticker-end">SAME MISSION. DIFFERENT LOCATION. <ArrowUpRight size={20}/></span></div></div>
  <section className="shell section" id="collection"><div className="section-heading"><div><span className="eyebrow">001 / THE FIRST COLLECTION</span><h2>GOOD GEAR.<br className="mobile-break"/> <span className="muted-heading">GREATER PURPOSE.</span></h2></div><p>Wear the work. Carry the mission.<br/>Make it your own.</p></div><Catalog featured/><div className="collection-note"><span>PRE-LAUNCH COLLECTION</span><p>Explore the designs. Final garments, sizing, and pricing will be confirmed before ordering opens.</p></div></section>
  <section className="story-section"><div className="shell story-grid"><div className="story-photo"><Artwork crop={{x:286,y:66,w:308,h:406}} alt="TechSavvy branded apparel lifestyle concept"/><span className="photo-label">BUILT AROUND PEOPLE.</span></div><div className="story-copy"><span className="eyebrow">002 / MORE THAN A LOGO</span><h2>THE WORK IS TECH.<br/>THE MISSION<br/>IS <span className="green">PEOPLE.</span></h2><p>Every install, every service call, every problem solved comes back to someone counting on you.</p><p className="muted">TechSavvy Gear brings that belief into what we wear. Original designs from Will Jackson, founder and Head Geek, for the people who show up and make things work.</p><Link href="/our-story" className="text-link">MEET THE MISSION <ArrowUpRight size={20}/></Link></div></div></section>
  <section className="shell values-strip"><div><Fingerprint/><div><h3>ORIGINAL BY DESIGN</h3><p>Created by TechSavvy. Rooted in the work.</p></div></div><div><Wrench/><div><h3>BUILT WITH INTENTION</h3><p>Samples first. Details that matter.</p></div></div><div><Heart/><div><h3>PEOPLE AT THE CENTER</h3><p>A small business with a human mission.</p></div></div></section>
  <section className="shell partner-banner"><div className="partner-number">003 / BUILD WITH US</div><div><h2>GOOD PEOPLE.<br/><span>GREAT POSSIBILITIES.</span></h2><p>We’re shaping the first collection—and opening conversations<br className="desktop-break"/> with production partners, collaborators, and community builders.</p></div><Link href="/partners" className="button button-dark">LET’S TALK PARTNERSHIP <ArrowRight size={20}/></Link></section>
  <section className="closing shell"><span>TECHSAVVY GEAR</span><p>Wired for What’s Next.</p><span>PEOPLE FIRST. ALWAYS.</span></section>
  </>;}
