import Link from 'next/link';
import { ArrowRight, Gem, Heart, Shirt, Truck, ShieldCheck } from 'lucide-react';
import { Artwork } from '@/components/artwork';
import { Catalog } from '@/components/catalog';
export const metadata={alternates:{canonical:'/'}};
export default function Home(){return <div className="draft-home">
  <section className="hero"><div className="hero-art"><Artwork crop={{x:282,y:65,w:658,h:408}} alt="TechSavvy apparel concept showing front and back designs with a branded service van" priority/></div><div className="hero-shade"/><div className="shell hero-content"><div className="eyebrow">TECHSAVVY GEAR</div><h1>PEOPLE<br/>SOLVE TECH.<br/>PEOPLE<br/>MATTER <span className="green">MORE.</span></h1><p>Premium apparel for the builders,<br/>troubleshooters, and problem solvers.</p><Link href="/shop" className="button button-green">SHOP THE COLLECTION <ArrowRight size={20}/></Link><div className="hero-trust"><div><Gem/><span>QUALITY<br/>IN THE DETAILS</span></div><div><Truck/><span>SHIPPING<br/>AT LAUNCH</span></div><div><Heart/><span>SUPPORTS<br/>A SMALL BUSINESS</span></div></div></div></section>
  <section className="shell section draft-collection" id="collection"><div className="section-heading"><h2>SHOP <span className="green">TECHSAVVY</span> APPAREL</h2><p>Quality gear for work, life, and everything in between.</p></div><Catalog featured/><p className="draft-preview-note">COLLECTION PREVIEW · Proposed prices and designs. Your cart saves on this device; ordering is not open yet.</p></section>
  <section className="shell values-strip draft-values"><div><Shirt/><div><h3>QUALITY IN THE DETAILS</h3><p>Physical samples before launch.</p></div></div><div><Truck/><div><h3>SHIPPING AT LAUNCH</h3><p>Delivery details coming soon.</p></div></div><div><ShieldCheck/><div><h3>PAYMENTS AT LAUNCH</h3><p>No payments collected in preview.</p></div></div><div><Heart/><div><h3>SUPPORTS A SMALL BUSINESS</h3><p>Every purchase will fuel the mission.</p></div></div></section>
  <section className="wear-banner"><div className="wear-art-left"><Artwork crop={{x:1,y:1330,w:310,h:166}} alt="People Matter shirt artwork concept"/></div><div className="wear-art-right"><Artwork crop={{x:636,y:1330,w:304,h:166}} alt="TechSavvy service van concept"/></div><div className="wear-banner-copy"><h2>WEAR THE MISSION.</h2><p>Wired for What’s Next.</p><Link href="/shop" className="button button-white">SHOP NOW <ArrowRight size={19}/></Link></div></section>
  <div className="shell draft-partner-link"><span>Help shape what comes next.</span><Link href="/partners">PARTNER WITH TECHSAVVY <ArrowRight size={16}/></Link></div>
  </div>;}
