'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Search, Plus, Minus, Check } from 'lucide-react';
import { products, colors, sizes, money, type Product, type Color, type Size } from '@/lib/catalog';
import { Artwork } from './artwork';
import { useCart } from './store';

export function ProductCard({product:p,initialColor}:{product:Product;initialColor?:Color}){
  const [color,setColor]=useState<Color>(initialColor||p.colors[0]);
  const [size,setSize]=useState<Size>('M'); const cart=useCart();
  return <article className="product-card"><Link className="product-image-link" href={`/shop/${p.slug}`} aria-label={`Explore ${p.name}, ${color}`}><Artwork crop={p.colorImages?.[color]||p.image} alt={`${p.name}, ${p.colorImages?.[color]?color:'Black'} design concept`}/><span className="product-image-label">DESIGN PREVIEW</span><span className="product-arrow"><ArrowUpRight size={21}/></span></Link><div className="product-card-body"><Link href={`/shop/${p.slug}`} className="product-name">{p.name}{p.id==='mission-tee'?' (Back Design)':''}</Link><p className="card-color">{color}{p.id==='logo-tee'&&color==='Black'?' (Primary)':''}</p><strong className="card-price">{money(p.price)}</strong><div className="swatches" aria-label={`${p.name} colors`}>{p.colors.map(c=><button key={c} title={c} aria-label={`${p.name}: ${c}`} aria-pressed={color===c} className={`swatch ${color===c?'selected':''}`} style={{'--swatch':colors[c]} as React.CSSProperties} onClick={()=>setColor(c)}/>)}</div>{color!=='Black'&&!p.colorImages?.[color]&&<span className="small muted">Black concept shown</span>}<label className="card-size"><span className="sr-only">Size for {p.name}, {color}</span><select value={size} onChange={e=>setSize(e.target.value as Size)}>{sizes.map(s=><option value={s} key={s}>Size: {s}</option>)}</select></label><button className="button button-green card-add" disabled={!cart.ready} onClick={()=>cart.add({productId:p.id,color,size,quantity:1})}>ADD TO CART</button></div></article>;
}
export function Catalog({initialCategory='All gear',featured=false}:{initialCategory?:string;featured?:boolean}){
  const [category,setCategory]=useState(initialCategory); const [sort,setSort]=useState('featured'); const [query,setQuery]=useState('');
  const filtered=products.filter(p=>p.active&&(category==='All gear'||p.category===category)&&`${p.name} ${p.description}`.toLowerCase().includes(query.toLowerCase()));
  if(sort==='price-low')filtered.sort((a,b)=>a.price-b.price);if(sort==='price-high')filtered.sort((a,b)=>b.price-a.price);if(sort==='name')filtered.sort((a,b)=>a.name.localeCompare(b.name));
  const shown=filtered.flatMap(p=>p.id==='logo-tee'?p.colors.map(color=>({product:p,color})):[{product:p,color:p.colors[0]}]);
  return <div><div className="catalog-toolbar"><div className="filter-tabs" aria-label="Filter collection">{['All gear','T-Shirts','Long Sleeve','Hoodies','Hats','Accessories'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)} className={category===c?'active':''}>{c==='All gear'?'ALL PRODUCTS':c.toUpperCase()}</button>)}</div><label className="sort-label"><span className="sr-only">Sort by</span><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Sort by: Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="name">Name</option></select></label></div>{!featured&&<div className="catalog-search"><Search size={18}/><input id="search" type="search" aria-label="Search products" placeholder="Find your gear…" value={query} onChange={e=>setQuery(e.target.value)}/><span className="small muted" aria-live="polite">{filtered.length} designs</span></div>}<div className="product-grid">{shown.map(({product:p,color})=><ProductCard key={`${p.id}-${color}`} product={p} initialColor={color}/>)}</div>{!shown.length&&<div className="empty-state"><h3>{['Long Sleeve','Hats','Accessories'].includes(category)?'More gear is taking shape.':'No gear found.'}</h3><p>{['Long Sleeve','Hats','Accessories'].includes(category)?`${category} are planned for a future collection. Explore our tees and hoodie in the meantime.`:'Try another search or explore all designs.'}</p><button className="button button-outline" onClick={()=>{setQuery('');setCategory('All gear');}}>VIEW ALL PRODUCTS</button></div>}</div>;
}
export function ProductDetail({product:p}:{product:Product}){
  const [color,setColor]=useState<Color>(p.colors[0]);const [size,setSize]=useState<Size|null>(null);const [quantity,setQuantity]=useState(1);const [error,setError]=useState('');const cart=useCart();
  return <div className="detail-grid"><div><div className="detail-art"><Artwork crop={p.colorImages?.[color]||p.image} alt={`${p.name} design concept`} priority/><span className="image-caption">{p.id==='mission-tee'?'BACK PRINT CONCEPT':'DESIGN CONCEPT'} / {p.colorImages?.[color]?color.toUpperCase():'BLACK'}</span></div><p className="small muted">Concept artwork supplied by TechSavvy. Final garment, placement, and printed color may differ. Physical samples are in development.</p></div><div className="detail-info"><span className="eyebrow">{p.label}</span><h1>{p.name}</h1><div className="detail-price">{money(p.price)} <span className="small muted">Proposed launch price</span></div><p className="lead">{p.statement}</p><p className="muted">{p.description}</p><fieldset><legend>COLOR <span>{color}</span></legend><div className="swatches large">{p.colors.map(c=><button key={c} className={`swatch ${c===color?'selected':''}`} style={{'--swatch':colors[c]} as React.CSSProperties} aria-label={c} aria-pressed={c===color} onClick={()=>setColor(c)}/>)}</div>{!p.colorImages?.[color]&&color!=='Black'&&<p className="small muted">Black concept shown. {color} photography is coming later.</p>}</fieldset><fieldset><legend>SIZE <Link href="/size-guide">Size guide ↗</Link></legend><div className="size-options">{sizes.map(s=><button key={s} aria-pressed={size===s} className={size===s?'selected':''} onClick={()=>{setSize(s);setError('');}}>{s}</button>)}</div></fieldset><div className="purchase-row"><div className="quantity"><button aria-label="Decrease quantity" disabled={quantity===1} onClick={()=>setQuantity(quantity-1)}><Minus size={16}/></button><span>{quantity}</span><button aria-label="Increase quantity" disabled={quantity===20} onClick={()=>setQuantity(quantity+1)}><Plus size={16}/></button></div><button className="button button-green" disabled={!cart.ready} onClick={()=>{if(!size){setError('Choose your size to add this design.');return;}cart.add({productId:p.id,color,size,quantity});}}>ADD TO PREVIEW BAG <Plus size={18}/></button></div>{error&&<p role="alert" className="form-error">{error}</p>}<p className="preview-notice"><Check size={16}/> Explore now. Ordering opens after sample approval.</p><div className="accordions">{[['The design',p.description],['Garment & care','The garment blank, fabric composition, care instructions, and manufacturer size chart will be published after physical samples are approved.'],['Shipping & returns','Ordering is not open yet. Delivery regions, processing times, shipping prices, and return terms will be confirmed before launch. Some future orders may ship in separate packages.']].map(([title,body])=><details key={title}><summary>{title}<Plus size={17}/></summary><p>{body}</p></details>)}</div><Link href="/partners" className="text-link">See a collaboration opportunity? Let’s talk <ArrowRight size={16}/></Link></div></div>;
}
