'use client';
import { useState, type FormEvent } from 'react';
import { ArrowUpRight, Check, Copy, Mail } from 'lucide-react';
import { settings } from '@/lib/catalog';
export function Inquiry({partner=false}:{partner?:boolean}){
  const [draft,setDraft]=useState(''); const [copied,setCopied]=useState(false);
  function prepare(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setDraft(`Hello TechSavvy,\n\n${data.get('message')}\n\nName: ${data.get('name')}\nEmail: ${data.get('email')}\n${partner?`Organization: ${data.get('organization')}\nInterest: ${data.get('interest')}\n`:''}`);setCopied(false);}
  return <div className="inquiry-panel"><span className="eyebrow">{partner?'START A CONVERSATION':'SAY HELLO'}</span><h2>{partner?'WHAT COULD WE BUILD?':'LET’S CONNECT.'}</h2><p className="muted">{partner?'Tell us a little about yourself and where you see a fit.':'Questions about the collection, the mission, or what’s next? We’d like to hear from you.'}</p><form onSubmit={prepare}><div className="form-pair"><label>Your name<input name="name" autoComplete="name" required maxLength={100}/></label><label>Email address<input name="email" type="email" autoComplete="email" required maxLength={200}/></label></div>{partner&&<><label>Company or organization <span className="muted">(optional)</span><input name="organization" autoComplete="organization" maxLength={150}/></label><label>I’m interested in<select name="interest"><option>Production & fulfillment</option><option>Brand collaboration</option><option>Community & events</option><option>Business partnership</option><option>Something else</option></select></label></>}<label>{partner?'Your idea':'Your message'}<textarea name="message" rows={5} required maxLength={3000} placeholder={partner?'What do you do, and how could we work together?':'What’s on your mind?'}/></label><button className="button button-green" type="submit">PREPARE EMAIL <ArrowUpRight size={18}/></button><p className="small muted">This prepares an email for you to send. Nothing is submitted or stored by this form.</p></form>{draft&&<div className="email-draft" role="status"><h3>Your message is ready.</h3><p>Open your email app to review and send it to <strong>{settings.email}</strong>, or copy the message.</p><pre>{draft}</pre><div className="draft-actions"><a className="button button-green" href={`mailto:${settings.email}?subject=${encodeURIComponent(partner?'TechSavvy Gear partnership inquiry':'TechSavvy Gear inquiry')}&body=${encodeURIComponent(draft)}`}><Mail size={16}/> OPEN EMAIL APP</a><button className="button button-outline" onClick={async()=>{try{await navigator.clipboard.writeText(draft);setCopied(true);}catch{setCopied(false);}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'COPIED':'COPY MESSAGE'}</button></div></div>}</div>;
}
